apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  labels:
    app: landing
spec:
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
        - name: landing
          image: ksox-web-landing
          envFrom:
            - secretRef:
                name: landing-secrets
            - configMapRef:
                name: landing-config
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 1000Mi
              cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: landing
spec:
  selector:
    app: landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
