apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed
spec:
  secretName: self-signed
  dnsNames:
    - exchange.test
    - landing.test
    - pay.test
    - static.test
  issuerRef:
    name: self-signed
