apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exchange
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - exchange.test
      secretName: self-signed
  rules:
    - host: exchange.test
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: exchange
                port:
                  number: 80
