apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pay
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - pay.ksox.finance
      secretName: ksox-finance
  rules:
    - host: pay.ksox.finance
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: pay
                port:
                  number: 80
